name: Deployment

concurrency:
  group: production
  cancel-in-progress: true

on:
  workflow_dispatch: # Allow running the workflow manually from the GitHub UI
  push:
    branches:
      - 'main'       # Run the workflow when pushing to the main branch

env:
  nuget_project : "\\AstronomyPictureOfTheDay\\AstronomyPictureOfTheDay.csproj"
  package_feed: "https://api.nuget.org/v3/index.json"
  nuget_folder: "\\packages"
  
jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
      - name: Restore dependencies
        run: dotnet restore AstronomyPictureOfTheDay/AstronomyPictureOfTheDay.csproj
      - name: Build
        run: dotnet build  AstronomyPictureOfTheDay/AstronomyPictureOfTheDay.csproj --no-restore --configuration Release 
      - name: Pack Nuget
        run: dotnet pack AstronomyPictureOfTheDay/AstronomyPictureOfTheDay.csproj --output ${{env.nuget_folder}} --no-build
      
      - name: publish Nuget Packages to GitHub
        run: dotnet nuget push packages/*.nupkg --source ${{env.package_feed}} --api-key ${{secrets.PUBLISH_TO_NUGET}} --skip-duplicate
